### ISSUE TITLE
Floating Button Action with Center docked don't work

### ISSUE THREAD

**Issue by Aaron1338** [insolite-dev/hidable#30] opened 2023-12-20 20:28 UTC
When you use the FloatingActionButton with FloatingActionButtonLocation.centerDocked the bottomNavigationBar is transparent and don't work. I don't know why this is happening. I send you a capture. Thank you.
![Simulator Screenshot - iPhone 14 Plus - 2023-12-20 at 21 26 51](https://github.com/insolite-dev/hidable/assets/138671340/771de7de-6b8c-4ca1-b069-52014c77ba1a)

**Comment by theiskaa** [comment] 2023-12-20 20:39
Thanks for the opening the issue, we will check it out as soon as possible.

**Comment by theiskaa** [comment] 2023-12-24 11:50
I tested with the centered floating action button, but it just worked fine, can you provide the full code and which version of hidable you're using?

**Comment by Aaron1338** [comment] 2024-01-02 13:54
Hi, thank you for respond, Im using the last version.

**Comment by Aaron1338** [comment] 2024-01-02 14:42
BottomAppBar(
        shape: widget.notchedShape,
        color: widget.backgroundColor,
        child: Row(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: items,
        ),
      ),
This is my code, it works with BottomNavigationAppBar but not with BottomAppBar.

**Comment by theiskaa** [comment] 2024-01-02 15:07
@Aaron1338 can you provide the full example, the one that is not working?

**Comment by Aaron1338** [comment] 2024-01-02 15:14
library curved_nav_bar;

import 'package:flutter/material.dart';
import 'package:curved_nav_bar/fab_bar/fab_bottom_app_bar_item.dart';
import 'package:hidable/hidable.dart';
import 'package:flutter_svg/svg.dart';
import 'package:ui_kit/src/widgets/navbar/fab_bottom_app_bar.dart';
import 'package:ui_kit/ui_kit.dart';

class CurvedNavBar extends StatefulWidget {
  /// list of [FABBottomAppBarItem] items
  /// length should be always even eg.- 2,4,6,8
  /// length of [appBarItems] should be equal to the length of [bodyItems]
  final List<FABBottomAppBarItem>? appBarItems;

  /// list of `widgets`
  /// length should be equal to [appBarItems]
  /// length of [bodyItems] should be equal to the length of [appBarItems]
  final List<Widget>? bodyItems;

  ///  then the [body] extends to the bottom of the Scaffold,
  ///   In this case specifying `extendBody: true` ensures that that scaffold's
  ///   body will be visible through the bottom navigation bar's notch.
  ///   [extendBody] default value always true
  final bool extendBody;

  /// [Color] of selected tab
  /// [activeColor] default value always [Colors.black]
  final Color? activeColor;

  /// [Color] of unselected tab
  /// [inActiveColor] default value always [Colors.black26]
  final Color? inActiveColor;

  /// background [Color] of navigation bar
  /// [navBarBackgroundColor] default value always [Colors.white]
  final Color? navBarBackgroundColor;

  /// Scaffold [body]
  /// when [actionButton] selected
  final Widget? actionBarView;

  final Function()? onCentralButtonTap;

  final int selectedIndex;

  final Function(int index)? onTapItems;

  final String? centerItemText;
  final ValueChanged<int> onUpdatePage;
  final bool showBottomNavBar;
  final ScrollController scrollController;

  CurvedNavBar({
    Key? key,
    required this.appBarItems,
    required this.bodyItems,
    required this.onUpdatePage,
    required this.selectedIndex,
    required this.showBottomNavBar,
    required this.scrollController,
    this.centerItemText,
    this.extendBody = true,
    this.activeColor = Colors.black,
    this.inActiveColor = Colors.black26,
    this.navBarBackgroundColor = Colors.white,
    this.actionBarView,
    this.onTapItems,
    this.onCentralButtonTap,
  }) : super(key: key) {
    assert(appBarItems != null);
    assert(bodyItems != null);
    assert(appBarItems!.length == bodyItems!.length);
  }

  @override
  State<CurvedNavBar> createState() => _CurvedNavBarState();
}

class _CurvedNavBarState extends State<CurvedNavBar> {
  @override
  Widget build(BuildContext context) {
    List<Widget> bottomAppBarList = [];
    bottomAppBarList.addAll(
      widget.appBarItems!.map((e) {
        int index = widget.appBarItems!.indexOf(e);

        return Container(
          width: MediaQuery.of(context).size.width /
              (widget.appBarItems!.length + 1),
          alignment: Alignment.center,
          child: InkWell(
            onTap: () {
              widget.onTapItems!(index);
            },
            child: Column(
              children: [
                const SizedBox(
                  height: AppSpaces.m,
                ),
                ClipRRect(
                  child: widget.selectedIndex == index
                      ? e.activeIcon
                      : e.inActiveIcon,
                ),
                const SizedBox(
                  height: AppSpaces.xxs,
                ),
                Text(
                  e.text ?? '',
                  style: Theme.of(context).textTheme.bodySmall!.copyWith(
                        color: widget.selectedIndex == index
                            ? widget.activeColor
                            : widget.inActiveColor,
                      ),
                ),
              ],
            ),
          ),
        );
      }),
    );
    bottomAppBarList.insert(
      2,
      SizedBox(
        width: MediaQuery.of(context).size.width /
            (widget.appBarItems!.length + 1),
      ),
    );
    return Stack(
      children: [
        Scaffold(
          resizeToAvoidBottomInset: false,
          extendBody: widget.extendBody,
          /* floatingActionButton: Hidable(
            controller: widget.scrollController,
            child: GestureDetector(
              behavior: HitTestBehavior.translucent,
              onTap: widget.onCentralButtonTap,
              child: Container(
                padding: const EdgeInsets.all(AppSpaces.xxs),
                decoration: const BoxDecoration(
                  gradient: LinearGradient(
                    colors: [
                      Color(0xFFFC0400),
                      Color(0xFFFF5500),
                      Color(0xFFFF8F63),
                    ],
                    begin: Alignment.bottomLeft,
                    end: Alignment.topRight,
                  ),
                  shape: BoxShape.circle,
                ),
                child: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: SvgPicture.asset(
                    'assets/images/svg/logo.svg',
                    width: 28,
                    height: 20,
                    colorFilter: const ColorFilter.mode(
                      Colors.white,
                      BlendMode.srcIn,
                    ),
                    package: PackageConstants.uiKit,
                  ),
                ),
              ),
            ),
          ), */
          /* floatingActionButtonLocation:
              FloatingActionButtonLocation.centerDocked, */
          bottomNavigationBar: Hidable(
            controller: widget.scrollController,
            preferredWidgetSize: const Size.fromHeight(100),
            child: FABBottomAppBar(
              onUpdatePage: widget.onUpdatePage,
              height: 100,
              inActiveColor: widget.inActiveColor,
              activeColor: widget.activeColor,
              notchedShape: const CircularNotchedRectangle(),
              onTabSelected: (index) {
                if (widget.onTapItems != null) widget.onTapItems!(index);
              },
              backgroundColor: widget.navBarBackgroundColor,
              items: widget.appBarItems ?? [],
              centerItemText: widget.centerItemText,
              selectedIndex: widget.selectedIndex,
            ),
          ),
          /* Hidable(
            controller: widget.scrollController,
            preferredWidgetSize: const Size.fromHeight(120),
            child: Stack(
              fit: StackFit.loose,
              alignment: Alignment.bottomCenter,
              children: [
                Container(
                  color: widget.navBarBackgroundColor,
                  child: SizedBox(
                    height: AppSpaces.xxl7a,
                    child: Row(
                      children: bottomAppBarList,
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(bottom: 0),
                  child: Column(
                    children: [
                      GestureDetector(
                        behavior: HitTestBehavior.translucent,
                        onTap: widget.onCentralButtonTap,
                        child: Container(
                          padding: const EdgeInsets.all(AppSpaces.xxs),
                          decoration: const BoxDecoration(
                            gradient: LinearGradient(
                              colors: [
                                Color(0xFFFC0400),
                                Color(0xFFFF5500),
                                Color(0xFFFF8F63),
                              ],
                              begin: Alignment.bottomLeft,
                              end: Alignment.topRight,
                            ),
                            shape: BoxShape.circle,
                          ),
                          child: Padding(
                            padding: const EdgeInsets.all(16.0),
                            child: SvgPicture.asset(
                              'assets/images/svg/logo.svg',
                              width: 28,
                              height: 20,
                              colorFilter: const ColorFilter.mode(
                                Colors.white,
                                BlendMode.srcIn,
                              ),
                              package: PackageConstants.uiKit,
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(
                        height: AppSpaces.xs,
                      ),
                      Text(
                        widget.centerItemText ?? '',
                        style: Theme.of(context)
                            .textTheme
                            .bodySmall!
                            .copyWith(color: widget.inActiveColor!),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ), */
          body: widget.bodyItems![widget.selectedIndex],
        ),
      ],
    );
  }
}

class DropDrownMenu {
  const DropDrownMenu({
    required this.isLargeCards,
    this.menuOptions,
    this.menuCommingSoonOptions,
    this.title = '',
  });

  final String title;
  final List<DropDrownItem>? menuOptions;
  final List<DropDrownItem>? menuCommingSoonOptions;
  final bool isLargeCards;
}

void modalBottomSheetMenu({
  required DropDrownMenu menu,
  required BuildContext context,
  required String comingSoonTitle,
}) {
  showModalBottomSheet(
    context: context,
    isScrollControlled: true,
    shape: const RoundedRectangleBorder(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(AppBorderRadius.m),
        topRight: Radius.circular(AppBorderRadius.m),
      ),
    ),
    builder: (context) => SizedBox(
      child: Padding(
        padding: const EdgeInsets.symmetric(
          horizontal: AppSpaces.m,
        ).copyWith(
          top: AppSpaces.xl,
          bottom: AppSpaces.s,
        ),
        child: SafeArea(
          child: menu.isLargeCards
              ? Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(menu.title),
                        GestureDetector(
                          onTap: () => Navigator.pop(context),
                          child: const Icon(
                            Icons.close,
                          ),
                        ),
                      ],
                    ),
                    ListView(
                      physics: const NeverScrollableScrollPhysics(),
                      shrinkWrap: true,
                      primary: false,
                      children: [
                        ...menu.menuOptions ?? [],
                      ],
                    ),
                  ],
                )
              : Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(menu.title),
                        GestureDetector(
                          onTap: () => Navigator.pop(context),
                          child: const Icon(
                            Icons.close,
                          ),
                        ),
                      ],
                    ),
                    CustomScrollView(
                      scrollDirection: Axis.vertical,
                      physics: const NeverScrollableScrollPhysics(),
                      shrinkWrap: true,
                      primary: false,
                      slivers: [
                        SliverToBoxAdapter(
                          child: Center(
                            child: Center(
                              child: GridView.count(
                                primary: false,
                                shrinkWrap: true,
                                childAspectRatio: (100 / 90),
                                crossAxisCount: 2,
                                padding: const EdgeInsets.all(5),
                                children: [
                                  ...menu.menuOptions ?? [],
                                ],
                              ),
                            ),
                          ),
                        ),
                        SliverToBoxAdapter(
                          child: Padding(
                            padding: const EdgeInsets.symmetric(
                              vertical: AppSpaces.m,
                            ),
                            child: Text(
                              comingSoonTitle,
                            ),
                          ),
                        ),
                        SliverToBoxAdapter(
                          child: Center(
                            child: Center(
                              child: GridView.count(
                                primary: false,
                                shrinkWrap: true,
                                childAspectRatio: (100 / 90),
                                crossAxisCount: 2,
                                padding: const EdgeInsets.all(5),
                                children: [
                                  ...menu.menuCommingSoonOptions ?? [],
                                ],
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
        ),
      ),
    ),
  );
}

class RocketLaunchMenu {
  const RocketLaunchMenu({
    required this.isLargeCards,
    required this.initialBottomSheetSize,
    required this.finalBottomSheetSize,
    this.menuOptions,
    this.menuCommingSoonOptions,
    this.title = '',
    this.showTopLine = true,
  });

  final String title;
  final double initialBottomSheetSize;
  final double finalBottomSheetSize;
  final List<Widget>? menuOptions;
  final List<Widget>? menuCommingSoonOptions;
  final bool isLargeCards;
  final bool showTopLine;
}

Future<void> modalRocketLaunchMenu({
  required RocketLaunchMenu menu,
  required BuildContext context,
  required String comingSoonTitle,
}) async {
  await showModalBottomSheet(
    context: context,
    isScrollControlled: true,
    backgroundColor: AppColors.neutralDarkBlack,
    shape: const RoundedRectangleBorder(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(AppBorderRadius.m),
        topRight: Radius.circular(AppBorderRadius.m),
      ),
    ),
    builder: (context) => DraggableScrollableSheet(
      expand: false,
      initialChildSize: menu.initialBottomSheetSize,
      maxChildSize: menu.finalBottomSheetSize,
      minChildSize: menu.initialBottomSheetSize,
      builder: ((context, scrollController) => Padding(
            padding: const EdgeInsets.symmetric(
              horizontal: AppSpaces.m,
            ),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                if (menu.showTopLine)
                  Padding(
                    padding: const EdgeInsets.only(top: AppSpaces.m),
                    child: Container(
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20),
                        color: AppColors.accentPrimarySoft,
                      ),
                      width: MediaQuery.of(context).size.width * 0.3,
                      height: 5,
                    ),
                  ),
                if (menu.title.isNotEmpty)
                  Padding(
                    padding: const EdgeInsets.only(
                      top: AppSpaces.m,
                      bottom: AppSpaces.xs,
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.max,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Expanded(
                          child: Center(
                            child: Text(
                              menu.title,
                              style: Theme.of(context).textTheme.displayMedium,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                Expanded(
                  child: ListView.builder(
                    controller: scrollController,
                    shrinkWrap: true,
                    itemCount: menu.menuOptions?.length ?? 0,
                    itemBuilder: (context, index) => menu.menuOptions![index],
                  ),
                ),
              ],
            ),
          )),
    ),
  );
}

typedef VoidCallbackWithContext = Function(BuildContext context);

class DropDrownItem extends StatelessWidget {
  const DropDrownItem({
    Key? key,
    this.onPressed,
    this.icon,
    this.title = '',
  }) : super(key: key);
  final String title;
  final VoidCallbackWithContext? onPressed;
  final IconData? icon;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(5),
      child: SizedBox(
        height: AppSpaces.xxl7 + 20,
        width: AppSpaces.xxl7 + 75,
        child: AIBSectionCard(
          model: AIBSectionCardModel(
            cardColor: Theme.of(context).colorScheme.background,
            type: AIBSectionCardType.normal,
            title: title,
            icon: icon,
            iconAlignment: Alignment.centerLeft,
          ),
          onPressed:
              onPressed.runtimeType == Null ? null : () => onPressed!(context),
        ),
      ),
    );
  }
}

This is my full code

**Comment by Aaron1338** [comment] 2024-01-02 15:15
Like I told you this component FABBottomAppBar, is created from BottomAppBar

**Comment by theiskaa** [comment] 2024-01-02 15:20
I can't properly test this code, cuz there is too much stuff that's not provided.
Can you push to some repository i can clone and test it out?
@Aaron1338

**Comment by Aaron1338** [comment] 2024-01-02 15:25
sorry, is a private code, I can't push it to a repository. We can have a call and I can give you some more details.

**Comment by theiskaa** [comment] 2024-01-02 15:26
Let's arrange. What's your timezone and have you joined our discord?

**Comment by Aaron1338** [comment] 2024-01-02 15:27
No, I live in Spain. Can you send me an invitation from your discord?

**Comment by theiskaa** [comment] 2024-01-02 15:31
[Join Insolite Discord](https://discord.gg/XSK7fCdaEp)

**Comment by Aaron1338** [comment] 2024-01-02 15:37
Can you send me an invitation via discord?. That url don't work. My id is Aaron1337#1356

**Comment by theiskaa** [comment] 2024-01-02 15:40
It shows that you've joined

**Comment by theiskaa** [comment] 2024-01-02 16:16
Talked on call, and issue is about approach of implementation not a bug from package.
I'm closing it, if anything changes feel free to reopen.

Thanks!

**Comment by itismrx** [comment] 2024-05-22 11:37
@theiskaa I run to the same issues. In my case, I was using [Animated Bottom Navigation Bar](https://pub.dev/packages/animated_bottom_navigation_bar). When I wrap both Bottom Nav Bar and the Centered Floating Button the nav bar wouldn't be shown.

**Closed** 2024-09-27 20:06 UTC
